function imageLoad()
    segment_b = love.graphics.newImage("assets/progresscolor 1/segment b.png")
    segment_b2 = love.graphics.newImage("assets/progresscolor 2/segment b.png")
    segment_b3 = love.graphics.newImage("assets/progresscolor 3/segment b.png")
    segment_m = love.graphics.newImage("assets/progresscolor 1/segment m.png")
    segment_m2 = love.graphics.newImage("assets/progresscolor 2/segment m.png")
    segment_m3 = love.graphics.newImage("assets/progresscolor 3/segment m.png")
    segment_r = love.graphics.newImage("assets/progresscolor 1/segment r.png")
    segment_r2 = love.graphics.newImage("assets/progresscolor 2/segment r.png")
    segment_r3 = love.graphics.newImage("assets/progresscolor 3/segment r.png")
    progressbar_img = love.graphics.newImage("assets/progresscolor 1/progressbar.png")
    progressbar_img2 = love.graphics.newImage("assets/progresscolor 2/progressbar.png")
    progressbar_img3 = love.graphics.newImage("assets/progresscolor 3/progressbar.png")
    logo_img = love.graphics.newImage("assets/progresscolor 1/logo.png")
    logo_img2 = love.graphics.newImage("assets/progresscolor 2/logo.png")
    logo_img3 = love.graphics.newImage("assets/progresscolor 3/logo.png")
    about_system = love.graphics.newImage("assets/progresscolor 1/about system.png")
    about_system2 = love.graphics.newImage("assets/progresscolor 2/about system.png")
    about_system3 = love.graphics.newImage("assets/progresscolor 3/about system.png")
    close = love.graphics.newImage("assets/progresscolor 1/close window.png")
end